### ISSUE TITLE
[PE-D][Tester A] Parsing of class subject

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F12-4/tp#162]
Typing e as an input will cause emath to be entered as the subject rather than english. It seems that shortened names are allowed even though the instructions say that it must be entered in full.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ichigh0st/ped#4

**Comment by totsukatomofumi** [comment]
is a bug because I did not meant to allow one character abbreviations of subject
