### ISSUE TITLE
[PE-D][Tester E] UG formatting

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F12-4/tp#166]
User guide is not well formatted 

![image.png](https://raw.githubusercontent.com/phyliciachristel/ped/main/files/b3314e65-46a2-40f8-adff-4ceb28129b9a.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: phyliciachristel/ped#2

**Comment by totsukatomofumi** [comment]
this one not fixed pls advice ty!

**Comment by asaierika** [comment]
fixed in the recent PR.
