### ISSUE TITLE
[PE-D][Tester C] Mark-up looks slightly off

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F12-4/tp#170]
![Screen Shot 2022-10-28 at 16.51.43.png](https://raw.githubusercontent.com/melissaharijanto/ped/main/files/2a582b30-439a-4921-93bb-402664af9a6f.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: melissaharijanto/ped#7

**Comment by ongwenpin** [comment]
Fixed
