### ISSUE TITLE
[PE-D][Tester B] Find feature does not work as described in the UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F12-4/tp#179]
Here, I have added a student using the input `add student n/John Doe p/12345678 a/Yishun e/johndoe@example.com s/Yishun Secondary l/Secondary 2`

![image.png](https://raw.githubusercontent.com/jeromehjj/ped/main/files/753a25dd-d5e5-4981-92cc-10d617fa412a.png)

When trying to use the find function, I keyed in `find n/john` while displaying the current list of students.

However, I am unable to find the student with the name `John Doe` and this is the result shown

![image.png](https://raw.githubusercontent.com/jeromehjj/ped/main/files/ac43feca-9e30-4ab2-8eee-d265c266116d.png)

This does not work when using other prefixes as well as for finding classes and tutors.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jeromehjj/ped#6

**Comment by tantzeyeong** [comment]
This happens due to a bug where an entity which does not have tags added to it cannot be searched by the find command. Will fix it.
