### ISSUE TITLE
[PE-D][Tester D] Not sure why is this class in the data base already

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F12-4/tp#182]
![Screenshot 2022-10-28 at 5.06.54 PM.png](https://raw.githubusercontent.com/nicolelim02/ped/main/files/594e6d7e-b5d2-4c77-b619-048c11695525.png)

**Steps performed:**
1. Enter `add class n/test t/12pm - 4pm s/math l/primary 9 d/friday`

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: nicolelim02/ped#5

**Comment by totsukatomofumi** [comment]
lmao

**Comment by totsukatomofumi** [comment]
change output message to be more specific

**Comment by totsukatomofumi** [comment]
or specify in UG
