### ISSUE TITLE
[PE-D][Tester A] Modifying the details of a class assigned in the JSON file

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F12-4/tp#191]
After modifying a detail (I changed the day to a different day) of a class directly in the JSON file studentaddressbook.json and attempting to unassign the class, the application will say that the class is unassigned. however, the entity tag is not removed from the person. unassign will continue to work on the same person as if the class is still assigned.

Furthermore, after changing the name of the equivalent class in the application, it can be assigned to the affected person. the app still shows that the faulty class is assigned however and there is no way to remove it except through the json file again.

I think this could be prevented if upon loading the json files, a check is done to see if a class that is equal to the assigned class exists in the address book. if it cannot be found in the address book then the class should not be added.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ichigh0st/ped#12

**Comment by totsukatomofumi** [comment]
tengwhye, help see this thx
