### ISSUE TITLE
[PE-D][Tester C] User Guide lacks a Getting Started section

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F12-4/tp#199]
![Screen Shot 2022-10-28 at 18.53.36.png](https://raw.githubusercontent.com/melissaharijanto/ped/main/files/58294307-d0d1-4245-a643-68908ab580eb.png)

The need for `Java 11` to install the application should be documented; or perhaps if this application does not need it, it would be good if the user knows how to get started.

I do not think it is ideal to just put it in `Troubleshooting`; users might disregard the application if they do not know how to start it.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: melissaharijanto/ped#16

**Comment by ongwenpin** [comment]
Added get started section to UG
