### ISSUE TITLE
[PE-D][Tester C] Inconsistent application naming throughout the user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F12-4/tp#202]
![Screen Shot 2022-10-28 at 19.20.12.png](https://raw.githubusercontent.com/melissaharijanto/ped/main/files/5cc4fcca-f5e6-4288-b147-afbfd4bd8a5c.png)

![Screen Shot 2022-10-28 at 19.20.22.png](https://raw.githubusercontent.com/melissaharijanto/ped/main/files/c4d26e8a-7797-4e2c-9de8-73cbe78504f6.png)
![Screen Shot 2022-10-28 at 19.20.33.png](https://raw.githubusercontent.com/melissaharijanto/ped/main/files/a13afec3-f4fc-434a-9a42-5b37a00b0605.png)
![Screen Shot 2022-10-28 at 19.20.43.png](https://raw.githubusercontent.com/melissaharijanto/ped/main/files/5b242313-1080-4fce-abbe-0e2270eccc60.png)
![Screen Shot 2022-10-28 at 19.21.06.png](https://raw.githubusercontent.com/melissaharijanto/ped/main/files/2b1f41db-246d-497f-895a-4af00b517596.png)

Personally, I feel like this is the most basic thing that should not be wrong; I understand that it might be confusing because it's just with an `s` or without, but standardization will make it professional.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: melissaharijanto/ped#19

**Comment by totsukatomofumi** [comment]
wenpin pls double check, ty
